docs: add documentation to endpoints
SonarMusic/Player pull request #46
Opened 2022-06-27 10:27 UTC by Patisson4

2022-07-11 13:08 UTC, Ar4eR-ValerA requested changes

2022-07-11 13:08 UTC, Ar4eR-ValerA commented on Sonar.Player/Sonar.Player.Api/Controllers/FilesController.cs
> +    /// Constructor lol
Хорошая дока.

2022-07-11 13:08 UTC, Ar4eR-ValerA commented on Sonar.Player/Sonar.Player.Api/Controllers/ImportController.cs
> +    /// Constructor lol
Хорошая дока.

2022-07-11 13:08 UTC, Ar4eR-ValerA commented on Sonar.Player/Sonar.Player.Api/Controllers/QueueController.cs
> +    /// Constructor lol
Хорошая дока.

2022-07-11 13:08 UTC, Ar4eR-ValerA commented on Sonar.Player/Sonar.Player.Api/Controllers/QueueController.cs
> +    /// <returns>Nothing</returns>
Вообще-то возвращает таску.

2022-07-11 19:22 UTC, Patisson4 commented on Sonar.Player/Sonar.Player.Api/Controllers/QueueController.cs
> +    /// <returns>Nothing</returns>
Command из CQRS возвращает Unit.Value обернутое в IActionResult. Твои предложения сюда написать?

2022-09-19 20:01 UTC, Walter-Rabbit approved these changes

2022-09-19 20:01 UTC, Walter-Rabbit commented on Sonar.Player/Sonar.Player.Api/Controllers/FilesController.cs
> +    /// <param name="form"></param>
Где? Что? А?

2022-09-19 20:06 UTC, merged